language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"
  - "15"

install:
  - npm install

before_script: >
  if  [[ $(node -v) =~ ^v14\.* ]]; then
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    chmod +x ./cc-test-reporter
    ./cc-test-reporter before-build
  fi

script: >
  if  [[ $(node -v) =~ ^v14\.* ]]; then
    npm run build && npm run test:cover;
  else
    npm run build && npm run test:unit;
  fi

after_script: >
  if  [[ $(node -v) =~ ^v14\.* ]]; then
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  fi

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "14"
      script: npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
